name = "ElectricityMarketData"
uuid = "b0cd3f9d-d3c7-4edf-bab9-a3123bf8ae8c"
authors = ["Andrew Rosemberg <arosemberg3@gatech.edu>, Andre Ramos <andreramosfdc@gmail.com> and Thiago Novaes <thiagonovaesb@poli.ufrj.br>"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
